### ISSUE TITLE
[Android] java.lang.NoSuchMethodError in UnityNotificationRestartOnBootReceiver.java

### ISSUE THREAD

**Issue by artyom-v** [Unity-Technologies/com.unity.mobile.notifications#139]
Unity v2020.3.25f1
Plugin v1.5.0

The plugin is not working on Android 6.0 and less.

`Fatal Exception: java.lang.NoSuchMethodError: No static method recoverBuilder(Landroid/content/Context;Landroid/app/Notification;)Landroid/app/Notification$Builder; in class Landroid/app/Notification$Builder; or its super classes (declaration of 'android.app.Notification$Builder' appears in /system/framework/framework.jar)
       at com.unity.androidnotifications.UnityNotificationRestartOnBootReceiver.onReceive(UnityNotificationRestartOnBootReceiver.java:43)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2921)
       at android.app.ActivityThread.access$1800(ActivityThread.java:179)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

This is because of Notification.Builder.recoverBuilder method is used in [UnityNotificationRestartOnBootReceiver.java](https://github.com/Unity-Technologies/com.unity.mobile.notifications/blob/f5251ebb3313d63bc84a0d6d40d56040923c9048/com.unity.mobile.notifications/Runtime/Android/Plugins/com/unity/androidnotifications/UnityNotificationRestartOnBootReceiver.java#L43) and this method was added in [API 24](https://developer.android.com/reference/android/app/Notification.Builder#recoverBuilder(android.content.Context,%20android.app.Notification)).

**Comment by aurimasc** [comment]
Fixed in master.
